config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root 'glucose_levels#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'home#index', as: :unauthenticated_root
    end
  end

  resources :glucose_levels, only: [:index,  :create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/glucose_level.rb
class GlucoseLevel < ApplicationRecord

  DAILY_LIMIT = 4

  belongs_to :user

  scope :between, -> (from_date, to_date) {
    where(created_at: from_date..to_date)
  }

  validates :level, :user_id, presence: true, numericality: {
    only_integter: true,
    greater_than: 0
  }
  validate :more_than_four_times_a_day

  class << self
    @@current_date = Time.now.utc.to_date
    def today
      between( @@current_date.beginning_of_day,  @@current_date.end_of_day)
    end

    def this_month
      between( (@@current_date - 1.month).at_beginning_of_month.beginning_of_day,  @@current_date.end_of_day)
    end

    def month_to_date
      between( @@current_date.at_beginning_of_month.beginning_of_day,  @@current_date.end_of_day)
    end
  end

  private

    def more_than_four_times_a_day
      if self.user.glucose_levels.today.size >= DAILY_LIMIT
        errors.add(:level, "can only enter 4 times a day!")
      end
    end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :glucose_levels

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private
  
  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    unauthenticated_root_path
   end
end

app/controllers/glucose_levels_controller.rb
class GlucoseLevelsController < ApplicationController
  before_action :authenticate_user!

  def index
    @daily_glucose_levels = current_user.glucose_levels.today
    @monthly_glucose_levels = current_user.glucose_levels.this_month
    @month_to_date_glucose_levels = current_user.glucose_levels.month_to_date
  end
  
  def create
    @glucose_level = GlucoseLevel.new(glucose_level_parameters)
    if @glucose_level.valid?
      @glucose_level.save
      redirect_to glucose_levels_path, notice: "Glucose level added successfully."
    else
      render :new
    end
  end

  def new
    @glucose_level = GlucoseLevel.new
  end

  private
    def glucose_level_parameters
      params.require(:glucose_level).permit(:level).merge(user_id: current_user.id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_name_from_email(user)
    user.email.split('@')[0].camelcase  
  end

  def todays_date
    Time.now.utc.strftime("%d %B, %Y")
  end

  def current_month
    "#{ (Time.now - 1.month).utc.strftime("%d %B, %Y")} - #{ Time.now.utc.strftime("%d %B, %Y")}"
  end
  
  def month_to_date_range
    "#{ Time.now.utc.at_beginning_of_month.strftime("%d %B, %Y")} - #{ Time.now.utc.strftime("%d %B, %Y")}"
  end
end

app/views/glucose_levels/_glucose_level_form.html.erb
<%= form_for @glucose_level do |form| %>

  <div class="row align-items-center justify-content-center mt-3">
    <div class="col-sm-2 col-4 text-end">
      <%= form.label "Glucose Level", class: "col-form-label" %>
    </div>
    <div class="col-sm-2 col-4">
      <%= form.number_field :level, step: 1, required: true, class: "form-control" %>
    </div>
    <div class="col-sm-2 col-4 text-start">
      <span class="text-dark">mg/dl</span>
    </div>
  </div>

  <div class="row align-items-center justify-content-center mt-3">
    <div class="col-sm-3 col-4">
      <p class="text-danger mb-0"><%= @glucose_level.errors.full_messages.join(", ") %></p>
    </div>
  </div>

  <div class="row align-items-center justify-content-center mt-3">
    <div class="col-sm-2 col-4">
      <%= form.submit  'Submit', class: "btn btn-success w-100" %>
    </div>
  </div>


<% end %>

app/views/glucose_levels/_table_content.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Created At</th>
      <th scope="col">Level (mg/dl)</th>
    </tr>
  </thead>
  <tbody>
    <% if glucose_levels.present? %>

      <% glucose_levels.each_with_index do |glucose_value, index|%>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= glucose_value.created_at.strftime("%d %B, %Y") %></td>
          <td><strong><%= glucose_value.level %></strong></td>
        </tr>
      <% end %>

    <% else %>

      <tr>
        <td colspan="3"><strong>No Records Found</strong></td>
      </tr>
    
    <% end %>

  </tbody>
  <% if glucose_levels.present? %>
    </tfoot>
      <% levels = glucose_levels.pluck(:level)%>
      <th class="text-success">Minimum: <%= levels.min %></th>
      <th class="text-danger">Maximum: <%= levels.max %></th>
      <th class="text-warning">Average: <%= levels.instance_eval { reduce(:+) / size.to_f } %></th>
    </tfoot>
  <% end %>
</table>

app/views/glucose_levels/index.html.erb
<div class="p-5 rounded text-center">
  <h2 class="mb-5">Glucose Level Report</h2>

  <div class="row justify-content-center mt-5">
    <div class="col-md-8 shadow">
      <h5 class="mb-4 mt-2 text-start text-info">Daily Report (<%= todays_date %>)</h5>
      <%= render "table_content", glucose_levels: @daily_glucose_levels %>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-md-8 shadow">
      <h5 class="mb-4 mt-2 text-start text-info">Montly Report (<%= current_month %>)</h5>
      <%= render "table_content", glucose_levels: @monthly_glucose_levels %>
    </div>
  </div>

  <div class="row justify-content-center mt-5">
    <div class="col-md-8 shadow">
      <h5 class="mb-4 mt-2 text-start text-info">Month to Date Report (<%= month_to_date_range %>)</h5>
      <%= render "table_content", glucose_levels: @month_to_date_glucose_levels %>
    </div>
  </div>

</div>

app/views/glucose_levels/new.html.erb
<div class="p-5 rounded text-center">

  <h2 class="mb-5">Welcome to Sweety App, <%= get_name_from_email(current_user) %></h2>

  <div class="row align-items-center justify-content-center mt-3">
    <div class="col-sm-6 col-12">
      <span class="text-muted">Please Enter the sugar level in the below input. You can enter 
      maximum of 4 times/day which will be good enough for tracking 
      the sugar levels.</span>
    </div>
  </div>

  <hr class="w-50 mx-auto"/>

  <%= render "glucose_level_form" %>

</div>

app/views/home/index.html.erb
<div class="p-5 rounded text-center">
  <h2 class="mb-5">Welcome to Sweety App</h2>
  <div class="row justify-content-center">
    <div class="col-md-3">
      <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-lg btn-success px-5 py-3' %>
    </div>
    <div class="col-md-3">
      <%= link_to 'Register', new_user_registration_path, class: 'btn btn-lg btn-outline-success px-5 py-3' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sweety</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <% if notice %>

      <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
        <p class="notice"><%= notice %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>

    <% end %>

    <% if alert %>

      <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
        <p class="notice mb-0"><%= alert %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>

    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid d-flex justify-content-between">
    <a class="navbar-brand" href="/">Sweety App</a>

    <% if user_signed_in? %>
      <div class="d-flex">
        <%= link_to 'Reports', glucose_levels_path, class: 'btn btn-dark' %>
        <%= link_to 'Enter Glucose Level', new_glucose_level_path, class: 'btn btn-dark' %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-dark' %>
      </div>
    
    <% end %>

  </div>
</nav>